### ISSUE TITLE
Give the user more information about UEFI/BIOS boot compatibility for our disk image

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-docs#100]
Let's add some information to the docs addressing https://discussion.fedoraproject.org/t/are-fedora-coreos-disk-images-hybrid-bios-uefi-bootable/21911/2

- add a FAQ entry for this
- add some helpful text in https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/
- not sure if there is anything about this we can add to https://docs.fedoraproject.org/en-US/fedora-coreos/platforms/

**Comment by nasirhm** [comment]
I would like to work on it.

**Comment by dustymabe** [comment]
Thanks!

**Comment by dustymabe** [comment]
fixed by #102
