### ISSUE TITLE
add tutorial to our documentation

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-docs#106]
It might be beneficial to add a tutorial like [what we did for devconf earlier this year](https://dustymabe.com/2020/01/23/devconf.cz-2020-fedora-coreos-lab/) to our documentation here. Should we consider trying to update the steps there, formalize the writing style, and add it to our docs somewhere?

**Comment by nasirhm** [comment]
A massive +1 for people to get test drive of CoreOS, If we're planning to add it, I can work on formalizing the writing style and add it in our docs. 

The advanced one's broken due to some issue. We would have to fix it as well.

**Comment by dustymabe** [comment]
Sounds good @nasirhm - thanks for picking this up. Please let me know when you hit issues. I think there are a few things that will need to be migrated.

**Comment by dustymabe** [comment]
Here is the source code (markdown, etc) for the session we did earlier this year that we can use as a starting point:  
https://github.com/dustymabe/dustymabe.com/tree/master/content/post/2020-01-23

**Comment by nasirhm** [comment]
Thank You @dustymabe , The advanced one has an issue. we would have to fix that as well.

**Comment by lucab** [comment]
I think we can add a `Tutorials` top section and then add sub-pages for specific topics.
