### ISSUE TITLE
Add Documentation or Links for Complex Network Setups

### ISSUE THREAD

**Issue by shawnweeks** [coreos/fedora-coreos-docs#107]
Or at least add some links to documentation that explains the network configuration options and format. For example I need to configure bonds and vlans on bare metal and I can't find any information about how to do it.

**Comment by dustymabe** [comment]
Thansk @shawnweeks. We'll try to do this as part of our documtation hackfest coming up. Here's what we'd like to document:


* complex network setups
    * NetworkManager & kargs examples for:
        * static ip
        * bonding
        * bridging
        * vlans?
        * bridges

**Comment by dustymabe** [comment]
Some good source for this can come from the manual testing script I wrote a while back: 

https://github.com/coreos/fedora-coreos-config/blob/d20f25bb8aa1461fde85a2981c4491703b038b95/tests/manual/coreos-network-testing.sh#L58-L231

**Comment by dustymabe** [comment]
I can work on adding docs for this.

**Comment by bgilbert** [comment]
This [exists now](https://docs.fedoraproject.org/en-US/fedora-coreos/sysconfig-network-configuration/).
