### ISSUE TITLE
provisioning: add "Booting on OpenStack" page

### ISSUE THREAD

**Issue by lucab** [coreos/fedora-coreos-docs#116]
The "Provisioning Machines" section is currently missing a "Booting on OpenStack" page.

We do publish qcow2.xz images for the `openstack` platform, but we do need instructions on how to import the image to an openstack platform and launch a VM based on that.

**Comment by dustymabe** [comment]
I can take this one if no one else gets to it during the hackfest. I have access to an openstack environment now.
