### ISSUE TITLE
Add documentation on how automatic system updates work

### ISSUE THREAD

**Issue by Limero** [coreos/fedora-coreos-docs#13]
There should be documentation on how the automatic system updates work. I can't find anything about it.
Is it a timer that is run occasionally? Does it restart the system? Does it cause any downtime?

**Comment by lucab** [comment]
I'm planning to tackle this one once the whole plan stabilizes a bit more. For the moment, I only have component-level documentation at https://github.com/coreos/zincati.

Just to scratch the surface:

> Is it a timer that is run occasionally?

Some how yes and somehow no. No, it is a background service (`zincati.service`). Yes, it periodically polls for new updates. See https://github.com/coreos/zincati/blob/master/docs/usage/auto-updates.md.

> Does it restart the system? Does it cause any downtime?

Yes to both. The long term plan is to let the sysadmin decide when/how a maintenance downtime is ok. See https://github.com/coreos/zincati/blob/master/docs/usage/updates-strategy.md.

Please do note that this is currently being developed, thus features are gradually landing with new FCOS release in the `testing` channel.

**Comment by Limero** [comment]
I find the current documentation to be describing all the parts well, so I'll close this :)

**Comment by dustymabe** [comment]
Thanks @Limero
