### ISSUE TITLE
Have dedicated page to document storage-related modifications

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-docs#131]
Right now, we have some storage examples nested in the "FCCT Specification" page. We should split that out into a dedicated "Configuring Storage" page. Examples of what this page could have:
- configuring `/var` (or submountpoints) on a separate partition on the primary disk
- configuring `/var` (or submountpoints) on a separate partition on a separate disk
- configuring `/var` on RAID

This will be prep as well for reconfiguring the root filesystem itself once we support that (https://github.com/coreos/fedora-coreos-tracker/issues/94).

**Comment by lucab** [comment]
Prior art: https://coreos.com/os/docs/latest/mounting-storage.html
