### ISSUE TITLE
The first tutorial error with virt-install 

### ISSUE THREAD

**Issue by doyoungim999** [coreos/fedora-coreos-docs#169]
When I run  the steps in https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-autologin/ :
# Start a Fedora CoreOS virtual machine
virt-install --name=fcos --vcpus=2 --ram=2048 --os-variant=fedora32 \
    --import --network=bridge=virbr0 --graphics=none \
    --qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=${PWD}/autologin.ign" \
    --disk=size=20,backing_store=${PWD}/fedora-coreos.qcow2

I received an error : 
[root@centos7 coreos]# virt-install --name=fcos --vcpus=2 --cpu host-passthrough  --ram=2048 --os-variant=fedora30 \
>     --import --network=bridge=virbr0 --graphics=none \
>     --qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=${PWD}/autologin.ign" \
>     --disk=size=20,backing_store=${PWD}/fedora-coreos.qcow2

Starting install...
Allocating 'fcos-1.qcow2'                                             |  20 GB  00:00:00
ERROR    internal error: process exited while connecting to monitor: qemu-kvm: -fw_cfg: invalid option
Removing disk 'fcos-1.qcow2'                                          |    0 B  00:00:00
Domain installation does not appear to have been successful.
If it was, you can restart your domain by running:
  virsh --connect qemu:///system start fcos
otherwise, please restart your installation.

--------------------------------------
I am trying to fix this issue and could not find. Is there anyone fix this issue?

**Comment by lucab** [comment]
As mentioned in https://github.com/coreos/ignition/blob/master/doc/supported-platforms.md, `fw_cfg` requires QEMU 2.4.0 or higher. Which version are you using?

**Comment by doyoungim999** [comment]
[root@centos7 download]# qemu-system-x86_64 -version

(process:45016): GLib-WARNING **: 04:07:06.367: gmem.c:489: custom memory allocation vtable not supported
QEMU emulator version 2.0.0, Copyright (c) 2003-2008 Fabrice Bellard

So I erased 
#yum erase qemu-kvm 
however I still can find the same version.
[root@centos7 download]# yum erase  qemu-kvm
Loaded plugins: fastestmirror, langpacks, product-id, search-disabled-repos, subscription-
              : manager

This system is not registered with an entitlement server. You can use subscription-manager to register.

No Match for argument: qemu-kvm
No Packages marked for removal
[root@centos7 download]# qemu-system-x86_64 -version

(process:45016): GLib-WARNING **: 04:07:06.367: gmem.c:489: custom memory allocation vtable not supported
QEMU emulator version 2.0.0, Copyright (c) 2003-2008 Fabrice Bellard

How can i fix ?

**Comment by doyoungim999** [comment]
My environment is centos7.8. 
qemu-kvm version is QEMU emulator version 1.5.3.
[root@bm01-redhat download]# /usr/libexec/qemu-kvm -version
QEMU emulator version 1.5.3 (qemu-kvm-1.5.3-173.el7_8.3), Copyright (c) 2003-2008 Fabrice Bellard

Which OS version supports qemu 2.4.0 ? 
I tried to install higher verion of qemu in different way and failed. 
I would appreciate your tip about qemu version.

**Comment by lucab** [comment]
QEMU 2.4 has been released in 2015, any Linux distribution with packages more recent than that should work. I'm not closely tracking Centos, but I think 8.x may have it or there may be additional repositories for 7.x.
Closing the ticket; if you have further issues please reach to Centos community channels for help.
