### ISSUE TITLE
Document /etc persistence across updates and reboots in FAQ

### ISSUE THREAD

**Issue by tomleb** [coreos/fedora-coreos-docs#174]
I could not find documentation about persistence when doing updates and reboots.

This could be documented in the FAQ.

So far the information I got from IRC is that updates will preserve changes by default and that `/etc` persist across reboots.

EDIT:
Further details from [machine-config-operator] which links to the [ostree adapting exists] page.

[machine-config-operator]: https://github.com/openshift/machine-config-operator/blob/master/docs/FAQ.md#q-if-i-change-something-manually-on-the-host-will-the-mco-revert-it
[ostree adapting exists]: https://ostree.readthedocs.io/en/latest/manual/adapting-existing/

>  Stated more generally, on an OSTree managed system, all content in /etc and /var is preserved by default across upgrades.

Confusingly, the second link only state that `/var` persists.

**Comment by lucab** [comment]
> Confusingly, the second link only state that /var persists.

That's one of those *technically true* statements: content in `/var` persists untouched, while files in `/etc` get versioned/coupled to deployments.
As such, stuff in `/etc` can change when booting into a different deployment (e.g. a rollback), while that property does not apply to data in `/var`.

In practice, the short statement "all content in /etc and /var is preserved by default across upgrades" is simpler to understand when talking about ephemeral state.

**Comment by tomleb** [comment]
What happens when a user writes something to `/etc` and it conflicts with a coreos update?
