### ISSUE TITLE
Is the documentation released under any license?

### ISSUE THREAD

**Issue by eriksjolund** [coreos/fedora-coreos-docs#175]
I don't see any _LICENSE_ or _COPYING_ file in the repository.

**Comment by lucab** [comment]
The footer at the bottom of https://docs.fedoraproject.org/en-US/fedora-coreos/ has the relevant details:
> All Fedora Documentation content available under CC-BY-SA 3.0 or, when specifically noted, under another accepted free and open content license.

**Comment by bgilbert** [comment]
Thanks for pointing this out.  #176 adds a LICENSE file.
