### ISSUE TITLE
Getting started docs don't reference the 'core' user

### ISSUE THREAD

**Issue by zmarano** [coreos/fedora-coreos-docs#186]
For example, the GCE doc tells you that you don't need to [customize the instance and you can SSH in](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-gcp/#_launching_a_vm_instance) but never how to do so. The only place the 'core' user is mentioned seems to be in the [container tutorial](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-containers/). The ask would be to add the basic here's how you use the 'core' user to SSH into a Fedora CoreOS VM in different environments in the getting started guides.

**Comment by nasirhm** [comment]
I would like to work on it

cc: @dustymabe

**Comment by dustymabe** [comment]
thanks @nasirhm! I would say maybe we should add a step to each of our "Provisioning Machines" pages docs that mention this. Like "Booting on AWS", "Booting on Azure", etc.

**Comment by lucab** [comment]
I'm confused about this report. The actual "Getting Started" page at https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/ actually mentions the `core` in several places already.

**Comment by bgilbert** [comment]
@lucab The individual provisioning pages don't, so after a new user provisions a system, it may not be clear what to do next.

**Comment by JaimeMagiera** [comment]
Given this request and https://github.com/coreos/fedora-coreos-tracker/issues/726#issuecomment-770361539, it might be worth having a page dedicated to explaining the core user and how to work with it. Happy to create such a page if folks agree.

**Comment by bgilbert** [comment]
@JaimeMagiera Deleting the core user should probably be a section on [this page](https://docs.fedoraproject.org/en-US/fedora-coreos/authentication/).  In addition, I still think there's value to adding a note on each of the `Booting on X` pages telling the user how to get into their new system.

**Comment by travier** [comment]
Clearing the assignee given that there hasn't been progress on this one yet. Feel free to work on it / request assignee.
