### ISSUE TITLE
coreos-installer related info missing

### ISSUE THREAD

**Issue by SaravanaStorageNetwork** [coreos/fedora-coreos-docs#192]
This issue is part of "Getting started" section - https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/

There is a mention to use coreos-installer to download the image. 
But, from where to download coreos-installer binary itself is not mentioned. 

Note: The path where it should be saved also needs be mentioned.

**Comment by lucab** [comment]
`coreos-installer` is available as a container (or directly as a binary on FCOS), see 
https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/.

**Comment by travier** [comment]
Also https://coreos.github.io/coreos-installer/getting-started/

**Comment by jlebon** [comment]
Added some docs in https://github.com/coreos/fedora-coreos-docs/pull/193 which should help new users.
