### ISSUE TITLE
Document recommended workflow for burning USB stick from Windows

### ISSUE THREAD

**Issue by pjvleeuwen** [coreos/fedora-coreos-docs#213]
Since I am a new FCOS user I might have a nice uninformed perspective. Via some tickets I will share some problems I ran into, in the hope that others might find them and be helped by it.

Please be aware that various ways of burning to USB stick may lead to different results. The purpose of this ticket is to see if we can **improve the documentation to include a 'known working approach'**.

Background :

When burning to a USB stick I get different response based on how I burn it:

Attempt 1:

* when burning "fedora-coreos-32.2020**1104**.3.0-live.x86_64.iso" with **tuxboot**-0.8.3.exe
* and booting in BIOS mode the booting halts with the message "no configuration file"
* when I provide the IGN filename it results in the messsage "booting kernel failed: invalid argument"
* it seems that the configuration file it is missing is an SYSLINUX CFG file
* trying all CFG files on the stick, like "EFI/fedora/grub.cfg", result in "failed to load COM32 file EFI/fedora/grub.cfg.c32"

Attempt 2:

* when burning "fedora-coreos-32.2020**1018**.3.0-live.x86_64.iso" with **tuxboot**-0.8.3.exe
* it fails while burning at the action "Running special E:\utils\win32\syslinux.exe on E:" which prompts Windows dialog "This file does not have an app associated with it..."

Attempt 3:

* when burning "fedora-coreos-32.2020**1018**.3.0-live.x86_64.iso" with **rufus**-3.13p.exe in "**ISO** Image mode"
* and booting in either BIOS or UEFI mode the CoreOS splash-screen comes by, but booting fails with message "failed to mount /run/media/iso"

Since this at least starts the CoreOS, so this suggests that rufus is a better alternative for tuxboot here!
Earlier problems with Ubuntu Live USB in the past made me switch from unetbootin to tuxboot based on the Ubuntu documentation.
It might be worth to document a 'known working setup' for FCOS in the documentation as apparently YMMV.

Attempt 4:

* when burning "fedora-coreos-32.2020**1018**.3.0-live.x86_64.iso" with **rufus**-3.13p.exe in "**DD** Image mode"
* and booting in the only available mode (unclear which it is) the CoreOS bash prompt comes up as expected

As we can see this took a lot of trial and error and the error messages above were not very helpful.

It might be worth to suggest in the documentation this known working approach for Windows: **"use rufus-3.13p.exe in DD Image mode"**

**Comment by bgilbert** [comment]
It sounds like you tried some tools that modify the image rather than writing it directly to the USB stick.  We should probably document a recommended Windows workflow which writes the image directly to the stick without changes.

**Comment by pjvleeuwen** [comment]
I tried making the changes in the form of a pull request. Make sure to check if I am using the correct branch, references, etc. For your consideration. Feel free to chuck it if you want to approach this differently :-)

**Comment by pjvleeuwen** [comment]
#215
