### ISSUE TITLE
different ways to get Live ISO give different result

### ISSUE THREAD

**Issue by pjvleeuwen** [coreos/fedora-coreos-docs#214]
Since I am a new FCOS user I might have a nice uninformed perspective. Via some tickets I will share some problems I ran into, in the hope that others might find them and be helped by it.

When I follow the instructions on 2020-12-05 on this page :
https://web.archive.org/web/20201206115935/https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/
then the resulting ISO is `fedora-coreos-32.20201104.3.0-live.x86_64.iso`.

Later I found that instead of the podman approach (which was quite a hassle for me) I was also able to just download the Live ISO from here :
https://web.archive.org/web/20201205115430if_/https://getfedora.org/coreos/download?tab=metal_virtualized&stream=stable
but the resulting ISO is `fedora-coreos-32.20201018.3.0-live.x86_64.iso`.

Point of this ticket is to suggest 3 small fixes:

1. make sure that the ISO from the getfedora.org page is up to date (seems to be older)
2. add a link on the docs.fedoraproject.org to the getfedora.org page
3. clarify on the docs.fedoraproject.org page whether we get stable, testing or next

**Comment by bgilbert** [comment]
1. coreos-installer and the web page both get the ISO URL from the exact same metadata source.  I wonder if your browser was caching an older version of the metadata?
2. We could do that.  The idea behind recommending coreos-installer instead of the download site was to encourage use of the latest OS release, rather than "download once and reuse".  (And also to verify GPG signatures, but the container image is unverified so that doesn't work.)
3. Yes, we should do that.  coreos-installer downloads `stable` unless a different stream is specified.

**Comment by pjvleeuwen** [comment]
@bgilbert Thanks for you quick response.

wrt 2 : In both cases the iso file is downloaded to file system. Since the coreos-installer approach is a lot more hassle I am more likely to keep that copy around as I do not want to repeat this process. If this is your aim, maybe it is better to provide an URL that always points to the latest stable / testing / next .

So in addition to https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/32.20201104.3.0/x86_64/fedora-coreos-32.20201104.3.0-live.x86_64.iso
also expose https://builds.coreos.fedoraproject.org/prod/streams/stable/x86_64/iso/latest/
(or similar)

Personally I use Windows with a Ubuntu 20.04 LTS VM as workstation. Due to problems with podman on 20.04 I had to set up a new Ubuntu 20.10 VM just for getting this download. Only to find out later that it was also available via the browser.

I cannot imagine any scenario where the podman approach is more user friendly then a simple curl / wget / browser download. While the intention was probably good, the result in my opinion is more complicated without real world benefit.

**Comment by pjvleeuwen** [comment]
I believe #216 provides the user clarity in his/her options. Also making the intention to use the latest version more explicit in the wording. Please note that I am new to contributing, so please double check that I did not incorrect branches or anything.

**Comment by bgilbert** [comment]
> Personally I use Windows with a Ubuntu 20.04 LTS VM as workstation. Due to problems with podman on 20.04 I had to set up a new Ubuntu 20.10 VM just for getting this download. Only to find out later that it was also available via the browser.
>
> I cannot imagine any scenario where the podman approach is more user friendly then a simple curl / wget / browser download. While the intention was probably good, the result in my opinion is more complicated without real world benefit.

There's currently no stable URL that always returns the latest image artifacts, so a straightforward curl isn't possible.  podman is a straightforward way to script the download for users that already have podman, but you're right that that doesn't help users on other OSes.

**Comment by pjvleeuwen** [comment]
@bgilbert Thanks for the clarification, I see the intention behind the current setup. Patch #216 is intended to help a wider range of users right now. Can you comment on that as well?

Also: how feasible is it to provide a stable URL that always returns the latest image artifact?

**Comment by bgilbert** [comment]
We provide a stable URL for a JSON file that contains the stable URL for the artifact.  That JSON file is what coreos-installer uses.  https://github.com/coreos/fedora-coreos-tracker/issues/625 discusses hosting a redirector driven by that JSON, though it's another service we'd need to maintain with a pretty high SLO.
