### ISSUE TITLE
Some command examples on the "Provisioning Fedora CoreOS on DigitalOcean" page could be more readable

### ISSUE THREAD

**Issue by woodrad** [coreos/fedora-coreos-docs#224]
The current version of the [Provisioning Fedora CoreOS on DigitalOcean](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-digitalocean/#_launching_a_droplet) documentation contains the following commands:

```shell
image_id=$(doctl compute image list-user | grep my-fcos-image | cut -f1 -d\ )
key_id=$(doctl compute ssh-key list | grep my-key | cut -f1 -d\ )
```
`cut -f1 -d\`, however, gives a syntax error. I believe `cut -f1 -d \t` is intended, as that command returns the droplet id and not an error. I will be submitting a PR for this shortly.

Thanks for all your hard work and consideration!

**Comment by bgilbert** [comment]
Nope, it's saying to cut on a space character.  Make sure you're not omitting the space between the backslash and closing paren.

**Comment by woodrad** [comment]
Ah, you are correct. Sorry about that!

**Comment by dustymabe** [comment]
> Sorry about that!

Don't be sorry. Thanks for being a contributor and trying to fix what you thought was a problem!

**Comment by lucab** [comment]
If it is less confusing, `cut -f1 -d ' '` has the same meaning.

**Comment by dustymabe** [comment]
> If it is less confusing, `cut -f1 -d ' '` has the same meaning.

Yeah, that is probably superior for this example. @woodrad - want to open a PR for that 👆?

**Comment by woodrad** [comment]
Sure thing!
