### ISSUE TITLE
user-guides: document user setup

### ISSUE THREAD

**Issue by lucab** [coreos/fedora-coreos-docs#23]
There are few dedicated options in FCCT/Ignition to manipulate GECOS user, but their documentation is a bit spotty. We can start from https://coreos.com/os/docs/latest/adding-users.html, polish that a bit, and add more FCCT examples.

Things I have in mind:
 - [ ] mention the default (privileged) administration user `core`
 - [ ] basic customizations to `core`: SSH keys, groups
 - [ ] how to add new users/groups
 - [ ] password generation and customization
 - [ ] sudo setup

**Comment by adriannemora** [comment]
I just stumbled on this now, as I'm still learning how to navigate github. I did mention `core` and explained how to add users and groups to the fcc file. I am adding a link to https://docs.fedoraproject.org/en-US/fedora/f31/system-administrators-guide/basic-system-configuration/Managing_Users_and_Groups/ for more basic instructions about to create and manage users and groups.

**Comment by jlebon** [comment]
We could rename the [Authentication page]("https://docs.fedoraproject.org/en-US/fedora-coreos/authentication/") to "Configuring Users", and expand that page instead.
