### ISSUE TITLE
iPXE instructions

### ISSUE THREAD

**Issue by jamescassell** [coreos/fedora-coreos-docs#233]
This should include setting `rootfs_url` and `initrd=initrd.img` for UEFI systems.

I'll send a PR eventually if no one gets to it first.

**Comment by bgilbert** [comment]
If you mean [this page](https://docs.fedoraproject.org/en-US/fedora-coreos/live-booting-ipxe/), the example does have `rootfs_url`, but `initrd=` is indeed missing.  Do you think we need to make the rootfs argument more prominent?

Incidentally, we should also clean up [this section](https://docs.fedoraproject.org/en-US/fedora-coreos/live-booting-ipxe/#_pxe_images) now that the rootfs transition has finished.

**Comment by lucab** [comment]
On the `initrd=` thing, I seem to remember this depends on the PXE firmware in use.
Modern iPXE should already take care of properly mapping the initrd. Which kind of issues are you seeing and in which environment? 

For context, the iPXE script in the docs linked above is known to work when loaded via iPXE 1.20.1 in BIOS mode, without further changes.

**Comment by bgilbert** [comment]
My understanding is based on [this appnote](https://ipxe.org/appnote/debian_preseed): on UEFI systems, the initrd gets loaded as a file in a virtual filesystem, but the kernel still needs the `initrd=` argument to know which file to read.  Is there reason to believe this has changed in newer iPXE releases?

**Comment by lucab** [comment]
@bgilbert no, I think your reference is better. This skew came up at some point in the past among openshift QA/docs teams and the final blame was put on an ancient iPXE firmware, without further reference. The above BIOS/UEFI difference seems more on-spot to me too.

**Comment by bgilbert** [comment]
Fix in https://github.com/coreos/fedora-coreos-docs/pull/282.
