### ISSUE TITLE
Document on how to embed the Ignition file into the ISO for bare-metal installations

### ISSUE THREAD

**Issue by rugk** [coreos/fedora-coreos-docs#245]
Maybe related to https://github.com/coreos/fedora-coreos-docs/issues/117 and I actually [found the solution here](https://discussion.fedoraproject.org/t/is-it-possible-to-modify-the-embedded-ignition-file-when-you-are-booted-up-in-the-live-iso/21743/5?u=rugk), but you should document on how to do a bare-metal installation without the HTTP server requirement for serving an ignition file.

**Use case:** I just want a simple bare-metal installation. No web server. No fancy stuff.

## Currently 

[This here](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/#_installing_from_live_iso) only explains the way we used to use in CD/DVD times, possibly, i.e. to burn an ISO image to a disk, boot the device and then on the device run a command to get the Ignition config to provision the device.
However, in times **of USB sticks** this is not really necessary anymore. You'd just place it on the thumb drive too and then embed it via `--ignition-file`… or better just directly embed it into the ISO with `coreos-installer iso ignition embed`.

IMHO the advertised way for bare metal installations with a web server is more cumbersome than it needs to be.

**Comment by bgilbert** [comment]
We should document it, but we need to make it usable first.  The Ignition config embedded by `coreos-installer iso ignition embed` is for the boot of the _live_ system, not the boot of the _installed_ system.  Currently, if you want to embed a config for the installed system, you need to add it as a file in the config for the live system, and then override `coreos-installer.service` to pass `--ignition-file`.  That works, and we partially document it [upstream](https://coreos.github.io/coreos-installer/customizing-install/#custom-coreos-installer-invocation), but it's too complex for common use.

Note, though, that installation via ISO is intended for one-off installs and for installation via LOM virtual CD media, not for typical installation at scale.  For the latter case, installing via PXE is much more flexible and customizable than going around to each machine with a USB stick.

**Comment by rugk** [comment]
Oh ok then I misunderstood that. Thanks for the information.
Also yeah, PXE is nice, but for a few machines, ISO is also good enough and this way would be useful.
