### ISSUE TITLE
Documentation Style Guide

### ISSUE THREAD

**Issue by JaimeMagiera** [coreos/fedora-coreos-docs#309]
It would be helpful to define style guidelines so that the contributors have a clear path to creating effective documentation that meets the needs of the community and is easily maintained by future contributors. 

To that end, a sub-working group could be formed to draft a style guide, which can then be run by the whole working group. The completed guide could be published on the site.

**Comment by dustymabe** [comment]
moved to https://github.com/coreos/fedora-coreos-tracker/issues/900
