### ISSUE TITLE
Add a breaking changes dashboard

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-docs#314]
Add a docs page that records the schedules for all upcoming compatibility breaks or behavior changes.  This could help reduce confusion if multiple deprecations are proceeding in parallel.

This page could also serve as a central repository for migration instructions, rather than leaving those in random docs pages for an extended period ([example](https://docs.fedoraproject.org/en-US/fedora-coreos/live-booting-ipxe/#_pxe_images)).

cc @travier

**Comment by travier** [comment]
Had initially made https://travier.github.io/fedora-coreos-tracker/ but it indeed does make more sense to have that in the docs.
