### ISSUE TITLE
user-guides: document wireguard setup via Ignition

### ISSUE THREAD

**Issue by lucab** [coreos/fedora-coreos-docs#43]
This is splitting off my comment from https://github.com/coreos/fedora-coreos-tracker/issues/362#issuecomment-583320187:

> Specifically, I'm interested in reaching a final UX flow where Ignition writes NM wireguard profiles (keyfiles) and secret material, and tunnel provisioning works without further custom scripting.

We should have a doc page showing how to perform this with `fcct` snippets.

(JL: Put under System Configuration in new "Configuring Network" subheading)

**Comment by jdoss** [comment]
I'll take this one.

**Comment by jlebon** [comment]
@jdoss, are you still planning to work on this issue?

**Comment by jdoss** [comment]
Yep I am going to do it tomorrow during the documentation hackfest at Nest.

**Comment by jdoss** [comment]
This can be closed as the docs were merged.
