### ISSUE TITLE
Improve remote-ign docs

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-docs#430]
We should discourage plain HTTP.  Let's switch to HTTPS and give examples of `gs` and `s3` URLs.

**Comment by dustymabe** [comment]
Talking about this page? https://docs.fedoraproject.org/en-US/fedora-coreos/remote-ign/

I think it would be useful to keep an `http` example because people are inevitably going to need it, but maybe add warnings/notes?
