### ISSUE TITLE
[main] Doc issue in file modules/ROOT/pages/provisioning-libvirt.adoc

### ISSUE THREAD

**Issue by PavelSosin-320** [coreos/fedora-coreos-docs#438]
It is not clear how to launch COS on the "native" Fedora 36 workstation using libvirt and qemu-kvm. This package offers qemu-system utility. I can't see how to pass qemu-system parameters correctly using virt-install. Is it possible to use qemu-system directly?

**Comment by travier** [comment]
If you're using libvirt, you can follow https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-libvirt/#_launching_a_vm_instance.

If you're using qemu directly, then you can add `-fw_cfg name=opt/com.coreos/config,file=${IGNITION_CONFIG}` to your command line.

**Comment by dustymabe** [comment]
Are you looking for how to boot on QEMU directly? See https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-qemu/

**Comment by dustymabe** [comment]
Closing this. As we have docs for both libvirt and QEMU.
