### ISSUE TITLE
Document memory requirements for LUKS root

### ISSUE THREAD

**Issue by skycastlelily** [coreos/fedora-coreos-docs#462]
I'm trying to automate testcases listed on [this page](https://docs.fedoraproject.org/en-US/fedora-coreos/storage/#_disk_layout)
According to instruction, encrypting a root filesystem should work,but it failed. 

```console
[root@ceph-03 ~]# virt-install --connect="qemu:///system" --name="${VM_NAME}" --vcpus="${VCPUS}" --memory="${RAM_MB}" \
        --os-variant="fedora-coreos-$STREAM" --import --graphics=none \
        --disk="size=${DISK_GB},backing_store=${IMAGE}" \
        --network bridge=virbr0 \
        --qemu-commandline="-fw_cfg name=opt/com.coreos/config,file=${IGNITION_CONFIG}"
....
....
[   27.114976] systemd[1]: Startup finished in 2.399s (kernel) + 0 (initrd) + 24.536s (userspace) = 26.936s.
[   27.117318] systemd[1]: run-credentials-systemd\x2dsysusers.service.mount: Deactivated successfully.
------
Ignition has failed. Please ensure your config is valid. Note that only
Ignition spec v3.0.0+ configs are accepted.

A CLI validation tool to check this called ignition-validate can be
downloaded from GitHub:
    https://github.com/coreos/ignition/releases
------

Displaying logs from failed units: ignition-disks.service
Sep 22 02:27:05 ignition[881]: disks: createLuks: op(2): executing: "wipefs" "-a" "/run/ignition/dev_aliases/dev/disk/by-partlabel/root"
Sep 22 02:27:05 ignition[881]: disks: createLuks: op(2): [finished] wiping filesystem signatures from "/run/ignition/dev_aliases/dev/disk/by-partlabel/root"
Sep 22 02:27:05 ignition[881]: disks: createLuks: op(3): [started]  creating "root"
Sep 22 02:27:05 ignition[881]: disks: createLuks: op(3): executing: "cryptsetup" "luksFormat" "--type" "luks2" "--key-file" "/tmp/ignition-luks-3117255530" "--label" "luks-root" "/run/ignition/dev_aliases/dev/disk/by-partlabel/root"
Sep 22 02:27:09 systemd[1]: ignition-disks.service: A process of this unit has been killed by the OOM killer.
Sep 22 02:27:09 systemd[1]: ress Enter for maintenance


Here is the butane file I used:

variant: fcos
version: 1.4.0
boot_device:
  luks:
    tpm2: true
passwd:
  users:
    - name: cloud-user
      groups:
        - wheel
      password_hash: xxx
      ssh_authorized_keys:
        - ssh-rsa xxxx

systemd:
  units:
    - name: rpm-ostree-install-python3.service
      enabled: true
      contents: |
        [Unit]
        Description=Layer vim with rpm-ostree
        Wants=network-online.target
        After=network-online.target
        # We run before `zincati.service` to avoid conflicting rpm-ostree
        # transactions.
        Before=zincati.service
        ConditionPathExists=!/var/lib/%N.stamp
        [Service]
        Type=oneshot
        RemainAfterExit=yes
        # `--allow-inactive` ensures that rpm-ostree does not return an error
        # if the package is already installed. This is useful if the package is
        # added to the root image in a future Fedora CoreOS release as it will
        # prevent the service from failing.
        ExecStart=/usr/bin/rpm-ostree install --apply-live --allow-inactive python3
        ConditionPathExists=!/var/lib/%N.stamp
        [Install]
        WantedBy=multi-user.target
storage:
  files:
    - path: /etc/ssh/sshd_config.d/20-enable-passwords.conf
      mode: 0644
      contents:
        inline: |
          # Fedora CoreOS disables SSH password login by default.
          # Enable it.
          # This file must sort before 40-disable-passwords.conf.
          PasswordAuthentication yes

```

Please feel free to tell if you need journal or /run/initramfs/rdsosreport.txt

**Comment by bgilbert** [comment]
Docs fix in https://github.com/coreos/fedora-coreos-docs/pull/463.

**Comment by skycastlelily** [comment]
Really thanks a lot for your Sooo quick response,I was busy with my work stuff.
After I set RAM to 4GiB,it still failed,here is some might useful log:
....
OK  ] Finished ignition-ostree-t… Ignition OSTree: Save Partitions.
[   25.505224] audit: type=1130 audit(1663829996.870:33): pid=1 uid=0 auid=4294967295 ses=4294967295 subj=kernel msg='unit=ignition-ostree-transposefs-save comm="systemd" exe="/usr/lib/systemd/systemd" hostname=? addr=? terminal=? res=success'
[   25.520256] systemd[1]: ignition-ostree-close-luks.service - Ignition OSTree: Close Secure Execution LUKS was skipped because of a failed condition check (ConditionPathExists=/run/coreos/secure-execution).
         Startin[   25.528748] systemd[1]: Starting ignition-disks.service - Ignition (disks)...
g ignition-disks.service - Ignition (disks)...
[   25.561213] ignition[813]: Ignition 2.14.0
[   25.563193] ignition[813]: Stage: disks
[   25.564836] ignition[813]: reading system config file "/usr/lib/ignition/base.d/00-core.ign"
[   25.568162] ignition[813]: reading system config file "/usr/lib/ignition/base.d/30-afterburn-sshkeys-core.ign"
[   25.572066] ignition[813]: no config dir at "/usr/lib/ignition/base.platform.d/qemu"
[   25.575008] ignition[813]: disks: createLuks: op(1): [started]  waiting for devices [/dev/disk/by-partlabel/root]
[   25.588199] ignition[813]: disks: createLuks: op(1): [finished] waiting for devices [/dev/disk/by-partlabel/root]
[   25.592946] ignition[813]: disks: createLuks: created device alias for "/dev/disk/by-partlabel/root": "/run/ignition/dev_aliases/dev/disk/by-partlabel/root" -> "/dev/vda4"
[   25.599007] ignition[813]: disks: createLuks: op(2): [started]  wiping filesystem signatures from "/run/ignition/dev_aliases/dev/disk/by-partlabel/root"
[   25.623301] ignition[813]: disks: createLuks: op(2): [finished] wiping filesystem signatures from "/run/ignition/dev_aliases/dev/disk/by-partlabel/root"
[   25.627733] ignition[813]: disks: createLuks: op(3): [started]  creating "root"
[     *] Job ignition-disks.service/start running (34s / no limit)
[   37.910124] ignition[813]: disks: createLuks: op(3): [finished] creating "root"
[   37.912256] ignition[813]: disks: createLuks: op(4): [started]  opening luks device root
[   40.028054] audit: type=1338 audit(1663830011.393:34): module=crypt op=ctr ppid=813 pid=1175 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="cryptsetup" exe="/usr/sbin/cryptsetup"[    **] Job ignition-disks.service/start running (36s / no limit)
[   40.043346] audit: type=1300 audit(1663830011.393:34): arch=c000003e syscall=16 success=yes exit=0 a0=6 a1=c138fd09 a2=557496c63ad0 a3=0 items=6 ppid=813 pid=1175 auid=4294967295 uid=0 gid=0 euid=0 suid=0 fsuid=0 egid=0 sgid=0 fsgid=0 tty=(none) ses=4294967295 comm="cryptsetup" exe="/usr/sbin/cryptsetup" subj=kernel key=(null)
[   40.049379] audit: type=1307 audit(1663830011.393:34): cwd="/"
[   40.050680] audit: type=1302 audit(1663830011.393:34): item=0 name=(null) inode=33 dev=00:07 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=unlabeled nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
[   40.054590] audit: type=1302 audit(1663830011.393:34): item=1 name=(null) inode=18144 dev=00:07 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=unlabeled nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
[   40.058564] audit: type=1302 audit(1663830011.393:34): item=2 name=(null) inode=22 dev=00:07 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=unlabeled nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
[   40.062509] audit: type=1302 audit(1663830011.393:34): item=3 name=(null) inode=18145 dev=00:07 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=unlabeled nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
[   40.066479] audit: type=1302 audit(1663830011.393:34): item=4 name=(null) inode=18145 dev=00:07 mode=040755 ouid=0 ogid=0 rdev=00:00 obj=unlabeled nametype=PARENT cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
[   40.070458] audit: type=1302 audit(1663830011.393:34): item=5 name=(null) inode=18146 dev=00:07 mode=0100444 ouid=0 ogid=0 rdev=00:00 obj=unlabeled nametype=CREATE cap_fp=0 cap_fi=0 cap_fe=0 cap_fver=0 cap_frootid=0
[   40.074476] audit: type=1327 audit(1663830011.393:34): proctitle=63727970747365747570006C756B734F70656E002F72756E2F69676E6974696F6E2F6465765F616C69617365732F6465762F6469736B2F62792D706172746C6162656C2F726F6F7400726F6F74002D2D6B65792D66696C65002F746D702F69676E6974696F6E2D6C756B732D31303632353032373334
[   40.205458] ignition[813]: disks: createLuks: op(4): [finished] opening luks device root
[   ***] Job ignition-disks.service/start running (50s / no limit)
[   54.368086] systemd[1]: ignition-disks.service: Main process exited, code=exited, status=1/FAILURE
[   54.370165] ignition[813]: disks failed
....
....

Displaying logs from failed units: ignition-disks.service
Sep 22 07:00:25 ignition[813]:         "contents": "[Unit]
Description=Layer vim with rpm-ostree
Wants=network-online.target
After=network-online.target
# We run before `zincati.service` to avoid conflicting rpm-ostree
# transactions.
Before=zincati.service
ConditionPathExists=!/var/lib/%N.stamp
[Service]
Type=oneshot
RemainAfterExit=yes
# `--allow-inactive` ensures that rpm-ostree does not return an error
# if the package is already installed. This is useful if the package is
# added to the root image in a future Fedora CoreOS release as it will
# prevent the service from failing.
ExecStart=/usr/bin/rpm-ostree install --apply-live --allow-inactive python3
ConditionPathExists=!/var/lib/%N.stamp
[Install]
WantedBy=multi-user.target
",
Sep 22 07:00:25 ignition[813]:         "enabled": true,
Sep 22 07:00:25 ignition[813]:         "name": "rpm-ostree-install-python3.service"
Sep 22 07:00:25 ignition[813]:       }
Sep 22 07:00:25 ignition[813]:     ]
Sep 22 07:00:25 ignition[813]:   }
Sep 22 07:00:25 ignition[813]: }
Sep 22 07:00:25 systemd[1]: Failed to start ignition-disks.service - Ignition (disks).
Sep 22 07:00:25 systemd[1]: ignition-disks.service: Triggering OnFailure= dependencies.
Sep 22 07:00:25 systemd[1]: ignition-disks.service: Consumed 47.069s CPU time.

Generating "/run/initramfs/rdsosreport.txt"


Entering emergency mode. Exit the shell to continue.
Type "journalctl" to view system logs.
You might want to save "/run/initramfs/rdsosreport.txt" to a USB stick or /boot
after mounting them and attach it to a bug report.

**Comment by bgilbert** [comment]
@skycastlelily Please file new bugs for new issues.  I've opened https://github.com/coreos/fedora-coreos-tracker/issues/1302.
