### ISSUE TITLE
document commands for bringing up VMs on s390x/ppc64le

### ISSUE THREAD

**Issue by dustymabe** [coreos/fedora-coreos-docs#467]
*Inspired by https://github.com/coreos/fedora-coreos-tracker/issues/1307*

We now have `s390x` and `ppc64le`. Let's update some of our examples to handle cases where `fw_cfg` doesn't work for those platforms.

- https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-libvirt/
- https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-qemu/

Need to be updated.

For libvirt the command floating around issue comments looks like:

```
virt-install ... --disk path=$PWD/config.ign,format=raw,readonly=on,serial=ignition
```

However we should investigate the `source.startupPolicy` argument to `--disk` to see if we can make it not fatal for the VM to boot if the Ignition file is later deleted.

```
source.startupPolicy
       It defines what to do with the disk if the source file is not accessible.
```

For QEMU:

```
-drive file=foobar.ign,if=none,format=raw,readonly=on,id=ignition \
  -device virtio-blk,serial=ignition,drive=ignition
```

**Comment by dustymabe** [comment]
@LakshmiRavichandran1 might be able to help us get this updated.

**Comment by LakshmiRavichandran1** [comment]
https://github.com/coreos/fedora-coreos-docs/pull/480/ could help here.
