### ISSUE TITLE
Add docs examples for "Add local file embedding for SSH keys and systemd units"

### ISSUE THREAD

**Issue by travier** [coreos/fedora-coreos-docs#511]
See https://github.com/coreos/butane/pull/289

**Comment by Okeanos** [comment]
During my work on the PR I created some local test files I can reuse. They are currently on [a branch](https://github.com/Okeanos/fedora-coreos-example/tree/embed-local) (I'll need to and will update) in [my fork](https://github.com/Okeanos/fedora-coreos-example) of [this example repo](https://github.com/horaios/fedora-coreos-example) and can be [seen here](https://github.com/horaios/fedora-coreos-example/compare/main...Okeanos:fedora-coreos-example:embed-local).

I'll see about creating a documentation PR for that.

The PR should probably target the following two sections of the tutorials I guess:

- [Setting up SSH access and starting containers at boot](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-containers/)
- [Starting a script on first boot via a systemd service](https://docs.fedoraproject.org/en-US/fedora-coreos/tutorial-services/)

If there's anything else you envision or a better placement for this please let me know.

**Comment by chanachai004** [comment]
50OFF100
