### ISSUE TITLE
Tutorial for Enabling autologin not working with VirtualBox

### ISSUE THREAD

**Issue by dragonbass13** [coreos/fedora-coreos-docs#542]
I was trying to follow the tutorial for enabling the autologin function on a fresh VirtualBox VM. My Ignition file looks exactly the same as what is specified in the tutorial. But, when the VM boots up, it does not autologin as intended, and instead stays at a login prompt. I am doing this from a Macbook Pro running Monterey. If this is a simple fix, I apologize.

Any updates to the documentation to clarify or help my issue would be appreciated. Thanks for all you do!
<img width="641" alt="Screen Shot 2023-05-04 at 2 13 07 AM" src="https://user-images.githubusercontent.com/30379842/236124832-6fdca677-ddd5-4a85-ade1-eaa6892fb2ea.png">

**Comment by bgilbert** [comment]
Just to check, could you post the Ignition config you're using?

**Comment by dragonbass13** [comment]
{
  "ignition": {
    "version": "3.3.0"
  },
  "storage": {
    "files": [
      {
        "path": "/etc/hostname",
        "contents": {
          "compression": "",
          "source": "data:,tutorial%0A"
        },
        "mode": 420
      },
      {
        "path": "/etc/profile.d/systemd-pager.sh",
        "contents": {
          "compression": "",
          "source": "data:,%23%20Tell%20systemd%20to%20not%20use%20a%20pager%20when%20printing%20information%0Aexport%20SYSTEMD_PAGER%3Dcat%0A"
        },
        "mode": 420
      }
    ]
  },
  "systemd": {
    "units": [
      {
        "dropins": [
          {
            "contents": "[Service]\n# Override Execstart in main unit\nExecStart=\n# Add new Execstart with `-` prefix to ignore failure`\nExecStart=-/usr/sbin/agetty --autologin core --noclear %I $TERM\n",
            "name": "autologin-core.conf"
          }
        ],
        "name": "serial-getty@ttyS0.service"
      }
    ]
  }
}

**Comment by dragonbass13** [comment]
<img width="1659" alt="Screen Shot 2023-05-04 at 2 33 36 AM" src="https://user-images.githubusercontent.com/30379842/236127800-d7a3a3a5-b12a-4fff-9eb7-46953acc05d8.png">

**Comment by bgilbert** [comment]
`serial-getty@ttyS0.service` only affects `ttyS0`, the first serial port, but your screenshot appears to be from the graphical console.  To enable autologin on the first graphical virtual console, you'll want `getty@tty1.service` instead.

**Comment by dragonbass13** [comment]
Gotcha. So I would need to change it to something like this, right?

<img width="1659" alt="Screen Shot 2023-05-04 at 2 41 19 AM" src="https://user-images.githubusercontent.com/30379842/236129175-1146eaf9-ea37-42a5-bdf9-43c22d5a6ade.png">

**Comment by dragonbass13** [comment]
That did it! Thanks very much, good sir!
