### ISSUE TITLE
[main] Doc issue in file modules/ROOT/pages/audit.adoc

### ISSUE THREAD

**Issue by NorthDecoder** [coreos/fedora-coreos-docs#631]
On page [fedora-coreos/audit](https://docs.fedoraproject.org/en-US/fedora-coreos/audit/)

When I run these commands, 
```bash
$ sudo auditctl --signal stop
$ sudo systemctl start  # Only if you want it started again
```
I get the response
```bash
Too few arguments.
```
I was expecting to stop and restart the daemon

**Comment by travier** [comment]
Thanks for the report. See: https://github.com/coreos/fedora-coreos-docs/pull/632
