### ISSUE TITLE
Document how to install Docker CE

### ISSUE THREAD

**Issue by jlebon** [coreos/fedora-coreos-docs#639]
This could be desirable for various reasons, e.g. more up to date packages or for a different channel.

See https://docs.docker.com/engine/install/fedora/.

**Comment by dustymabe** [comment]
@hrismarin - would you be interested in trying this out? it would basically be something like https://docs.fedoraproject.org/en-US/fedora-coreos/os-extensions/ but with an `rpm-ostree override remove moby-engine` first

**Comment by hrismarin** [comment]
Will this be in the FAQ or on a separate page? I'm in favor of a separate page, so we can give the necessary instructions and example config.

**Comment by jshuffle** [comment]
> @hrismarin - would you be interested in trying this out? it would basically be something like https://docs.fedoraproject.org/en-US/fedora-coreos/os-extensions/ but with an `rpm-ostree override remove moby-engine` first

I think it requires a slightly more extensive: `rpm-ostree override remove containerd moby-engine runc`

At least, that's what I've had to do, since the `docker-ce` repository ships a `containerd.io` package (which also contains `/usr/bin/runc`).

**Comment by dustymabe** [comment]
> Will this be in the FAQ or on a separate page? I'm in favor of a separate page, so we can give the necessary instructions and example config.

@hrismarin I'm not sure, I think the proposal of a separate page could make sense. I figure the people who care where it should be put will show up when there is a PR to review.

**Comment by dustymabe** [comment]
fixed in #641
