### ISSUE TITLE
Raw and Raw (4k Native) bare metal install options are not documented

### ISSUE THREAD

**Issue by kparal** [coreos/fedora-coreos-docs#78]
The [current bare metal documentation](https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/) says:

> This guide provides instructions to install Fedora CoreOS to bare metal. Two options are available:
> * Installing from live ISO
> * Installing from PXE

However, when you look at the [download page](https://getfedora.org/coreos/download?tab=metal_virtualized&stream=stable), you'll not only see **ISO** and **PXE**, but also **Raw** and **Raw (4k Native)**. Those two options are not documented.

Especially for "Raw (4k Native)", it's very unclear what it is. "4k" is most commonly known as a display resolution. So not only this would benefit from having documentation, but even renaming the download option to make it more clear would help a lot as well. We don't need to save on characters, so naming them e.g. `Raw disk image` and `Raw disk image (native 4KB sectors)` could go a long way.

**Comment by jlebon** [comment]
We don't have any documentation either right now which directly talks about the metal image.
What we can do is expand the "Installing on Bare Metal" page to include things like:
- using a metal image URL directly
- 512b vs 4k metal disks
- BIOS/UEFI support

**Comment by lucab** [comment]
Do note that this slightly intersects with https://github.com/coreos/fedora-coreos-docs/issues/117#issuecomment-666220590.

**Comment by jlebon** [comment]
Fix in https://github.com/coreos/fedora-coreos-docs/pull/144!
