### ISSUE TITLE
user-guides: make AWS guide more clear for non-ignition login

### ISSUE THREAD

**Issue by coremodule** [coreos/fedora-coreos-docs#79]
I have noticed on the AWS CoreOS user guide[0], there is no mention of what user to login as if the user does not spin up the machine with an ignition file. This is fairly confusing. Can this be changed/modified to show that the user can log into the machine using the “core” account?

[0] https://docs.fedoraproject.org/en-US/fedora-coreos/getting-started/

**Comment by lucab** [comment]
Thanks for the report. Yes I think we can add that, but the real fix would be documenting all of that a https://github.com/coreos/fedora-coreos-docs/issues/23.

**Comment by lucab** [comment]
I think https://github.com/coreos/fedora-coreos-docs/pull/81 should cover the immediate friction reported here.
