### ISSUE TITLE
ign-storage.adoc is missing in nav.adoc

### ISSUE THREAD

**Issue by grantral** [coreos/fedora-coreos-docs#82]
https://docs.fedoraproject.org/en-US/fedora-coreos/ign-storage/

**Comment by lucab** [comment]
Thanks for the report. Unless I'm missing some nuances, this should be the expected setup. That file is only meaningful in the larger context of https://github.com/coreos/fedora-coreos-docs/blob/master/modules/ROOT/pages/fcct-config.adoc which is correctly including it.

**Comment by grantral** [comment]
Yes, I just saw it. Thanks.
