### ISSUE TITLE
wipe_partition_entry default is unknown

### ISSUE THREAD

**Issue by kparal** [coreos/fedora-coreos-docs#83]
At https://docs.fedoraproject.org/en-US/fedora-coreos/fcct-config/#_disks there is:
```
wipe_partition_entry (boolean, optional)
    true: Ignition erases any existing partition that does not match this entry.
    false: Ignition leaves the partition unchanged, which will fail.
```
However, it is not defined what the default value is.

**Comment by bgilbert** [comment]
The [config spec](https://github.com/coreos/fcct/blob/master/docs/configuration-v1_1.md) does define it (`false`) so this is a problem in the downstream docs.

**Comment by kparal** [comment]
A similar problem is under https://docs.fedoraproject.org/en-US/fedora-coreos/fcct-config/#_file_systems:
```
wipe_filesystem (boolean, optional): If true, the device is wiped before the file system is created.
```

**Comment by bgilbert** [comment]
We've concluded internally that the separate derived documentation is insufficiently maintainable relative to its value.  The plan is to delete the reworded copy of the config spec and just refer users to the actual config spec.

**Comment by bgilbert** [comment]
Closing in favor of https://github.com/coreos/fedora-coreos-docs/issues/208.  Thanks for the report.
