### ISSUE TITLE
Default login for Fedora core os either undocumented or missing

### ISSUE THREAD

**Issue by pbokoc** [coreos/fedora-coreos-docs#89]
This was originally reported in Red Hat Bugzilla, I'm copying it here for visibility. https://bugzilla.redhat.com/show_bug.cgi?id=1802159

**Description of problem:**

I was just giving Fedora Core OS a first try and installed it from the ISO image to the bare metal following the instructions at

https://docs.fedoraproject.org/en-US/fedora-coreos/bare-metal/

Since I didn't have an ignition file yet, I just ran 

sudo coreos-installer install /dev/sda  

with out the ignition file, and this worked. 

After rebooting, the system came up, but I could not login on the console. The Docs do not contain a hint about what username and what password to use. When i mounted the file system on a different linux machine I saw that there is a core use with no password set. Since I'm not familiar with ostree, I wasn't sure whether I was breaking anything if I just changed the password in the /etc/shadow on that disk, and this is probably not the intended way to use the system. 

You end up with having a system that's of no use since you can't login. 

Either the docs should tell how to login after plain install, or coreos-installer should prevent from installing a system with no use and no login.

**Comment by lucab** [comment]
Thanks for forwarding from BZ! Current docpages are already covering this in several places, the most explicit one is https://docs.fedoraproject.org/en-US/fedora-coreos/authentication/#_using_password_authentication which says:
>  Fedora CoreOS ships with no default passwords. You can use a Fedora CoreOS Config to set a password for a local user [...]

> The configured password will be accepted for local authentication at the console. By default, Fedora CoreOS does not allow password authentication via SSH.

The same page contains actionable config snippets to configure password and SSH keys for the `core` user.

**Comment by lucab** [comment]
Looking at the timeline, I think we fixed this in between the original report and this ticket, so I'm going ahead and just close this as fixed already.

**Comment by barukasu** [comment]
so what is the default password for the `root` user? No password doesn't work with fedora 34.

**Comment by bgilbert** [comment]
There are no default passwords.  See [these docs](https://docs.fedoraproject.org/en-US/fedora-coreos/authentication/#_using_password_authentication).

**Comment by barukasu** [comment]
I used the OVA file with ESXI and it booted to a terminal. I have no option to submit a config file. It prompts for a username/pass, and `root` with no password doesn't work.

**Comment by bgilbert** [comment]
You can store your Ignition config in [guestinfo properties](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-vmware/#_encoding_ignition_configuration).  If that isn't working for you, please open a bug [here](https://github.com/coreos/fedora-coreos-tracker/issues/new/choose).

**Comment by barukasu** [comment]
guestinfo works with VSphere. I'm using ESXI without VSphere.

**Comment by bgilbert** [comment]
guestinfo should work in all VMware products.  You may need to manually modify the `.vmx` file.

**Comment by happyrwandan** [comment]
Ok, that's fine that you wanna edit multiple places to be able to login to Fedora CoreOS. how about if you downloaded a .Qcow2 image, and run that, all you can see is Fedora login, that's all. My virtual environment is not vwmare or virtualbox. Can't you guys think straight forward? just create a default long for Fedora CoreOS and make everyone's life easier. it's that simple. Why do you have to make everything complicated?

**Comment by bgilbert** [comment]
On all supported platforms, the general flow for configuring Fedora CoreOS is to write a [Butane config](https://coreos.github.io/butane/specs/), use [Butane](https://coreos.github.io/butane/) to convert it to an [Ignition](https://coreos.github.io/ignition/) config, and pass the Ignition config to the machine via cloud userdata or equivalent.  This is probably different than the workflow you're familiar with, and does take some getting used to.  The benefit, though, is that you can provision many machines with the same config &mdash; on cloud, VM, or bare metal &mdash; and that config encapsulates all of the differences between those machines and the default configuration.

For more details on how to do this for your particular platform, see the "Provisioning Machines" section of the [Fedora CoreOS documentation](https://docs.fedoraproject.org/en-US/fedora-coreos/).  For QEMU in particular, see [the QEMU provisioning guide](https://docs.fedoraproject.org/en-US/fedora-coreos/provisioning-qemu/).

I'm locking this issue to prevent additional support questions from accumulating here.  If you encounter an issue that isn't addressed by the documentation linked above, please feel free to open a new issue.
