### ISSUE TITLE
Document how to prevent rootfs resizing from taking up the whole disk

### ISSUE THREAD

**Issue by bgilbert** [coreos/fedora-coreos-docs#98]
The trick is to create a data partition at an appropriate offset using Ignition `start_mib`, such that the root FS gets resized to the desired size.

**Comment by cgwalters** [comment]
There was some ticket where we had a discussion on this I can't find.  I agree that that using `start_mib` is the trick today, but I think we can do better than that.  (Though I guess discussing implementing that is outside a docs issue)

**Comment by jlebon** [comment]
There's also the related problem of documenting how to prevent a new data partition from trapping the rootfs, which is solved a similar way. These together could be part of the new storage-related page (#131).

I think we're mostly agreed though that the current UX for this is not great. But we should still document this for now.

**Comment by cgwalters** [comment]
The other thing about this is we need guidelines for minimum sizes.  I would say 10G is totally a safe minimum that we should never exceed - anyone dealing with enough data they want to partition should be comfortable giving us 10G I think.  Likely even 5G would be fine, but these days of Big Data a GB here and there is nothing.

**Comment by bgilbert** [comment]
The storage page now has a [warning](https://docs.fedoraproject.org/en-US/fedora-coreos/storage/) about the minimum rootfs size and a [section](https://docs.fedoraproject.org/en-US/fedora-coreos/storage/#_sizing_the_root_partition) about how to set the size.  The `start_mib` trick is no longer necessary, since we have `resize: true` now.
